export class Constants {

    static HAS_SIGNED_IN = 'HAS_SIGNED_IN';

    static SIGN_IN = 'SIGN_IN';
    static SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
    static SIGN_IN_FAILED = 'SIGN_IN_FAILED'

    static LOG_OUT = 'LOG_OUT';
    static LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

    static ADD_PRODUCT = "ADD_PRODUCT";
    static ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
    static ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

    static VIEW_PRODUCT = "VIEW_PRODUCT";
    static VIEW_PRODUCT_SUCCESS = "VIEW_PRODUCT_SUCCESS";
    static VIEW_PRODUCT_FAILED = "VIEW_PRODUCT_FAILED";

    static ADD_STORE = "ADD_STORE";
    static ADD_STORE_SUCCESS = "ADD_STORE_SUCCESS";
    static ADD_STORE_FAILED = "ADD_STORE_FAILED";

    static VIEW_STORE = "VIEW_STORE";
    static VIEW_STORE_SUCCESS = "VIEW_STORE_SUCCESS";
    static VIEW_STORE_FAILED = "VIEW_STORE_FAILED";

    static ADD_PURCHASE = "ADD_PURCHASE";
    static ADD_PURCHASE_SUCCESS = "ADD_PURCHASE_SUCCESS";
    static ADD_PURCHASE_FAILED = "ADD_PURCHASE_FAILED";

    static VIEW_PURCHASE = "VIEW_PURCHASE";
    static VIEW_PURCHASE_SUCCESS = "VIEW_PURCHASE_SUCCESS";
    static VIEW_PURCHASE_FAILED = "VIEW_PURCHASE_FAILED";

    static ADD_SALE = "ADD_SALE";
    static ADD_SALE_SUCCESS = "ADD_SALE_SUCCESS";
    static ADD_SALE_FAILED = "ADD_SALE_FAILED";

    static VIEW_SALE = "VIEW_SALE";
    static VIEW_SALE_SUCCESS = "VIEW_SALE_SUCCESS";
    static VIEW_SALE_FAILED = "VIEW_SALE_FAILED";

    static VIEW_STOCK = "VIEW_STOCK";
    static VIEW_STOCK_SUCCESS = "VIEW_STOCK_SUCCESS";
    static VIEW_STOCK_FAILED = "VIEW_STOCK_FAILED";

    static LOGOUT = "LOGOUT";

}

